# Generated by Django 4.0.3 on 2022-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('booktitle', models.CharField(max_length=500)),
                ('authorname', models.CharField(max_length=500)),
                ('currentlyout', models.BooleanField()),
                ('numcheckedout', models.IntegerField()),
            ],
        ),
    ]
